### ISSUE TITLE
Subscriber in the forum

### ISSUE THREAD

**Issue by pax77-dd** [moodle-an-hochschulen/moodle-availability_role#20]
Hello,
I have observed the following behavior of the Restriction by course role plugin:
In a course there are three roles: Leader, Assistant and Participant
A course section is only accessible for leader and assistant. In the course section there is the moodle standard forum. In the subscriber list of the forum there are also the participants. However, during a test I could not see that the participants also receive a message from the forum via email. They also do not seem to have access to the course section and the forum activity. 
It is just a bit confusing that they just appear in the subscriber list. Maybe this bug can be fixed.
Best regards
Remo

**Comment by abias** [comment]
Hi @pax77-dd ,

thank you for raising this issue.
I was able to reproduce your findings and saw that a participant is listed in the forum subscriber list if the forum was set to "automatic subscription" even if the participant was not able to access the forum activity due to a access restriction. However, this was independent from the restriction type. I saw this behaviour for this availability plugin, but I saw the same for the date availability restriction.

In the end, I assume that this is a glitch in the forum subscriber list in Moodle core, but not an issue of this plugin.

Cheers,
Alex
